### ISSUE TITLE
Password should not be commited

### ISSUE THREAD

**Issue by ChienliMa** [ChienliMa/PatientNetwork#1]
https://github.com/ChienliMa/PatientNetwork/blob/ae5e39b72bab897c0e7158b11e290bc7e1cc03eb/server/patnet/src/patnet/dal/ConnectionManager.java#L41

Please create  ```context.xml``` file under ```META-INF``` and setup JDBC connection there. And add a gitignore to ignore that file.  [Example](https://www.journaldev.com/2513/tomcat-datasource-jndi-example-java)

**Comment by dilip7** [comment]
I read up from the link. 

IMH it is TME. 

Let's just do like prof has done.

Security is not important here anyway.
